################################
## Airflow Scheduler ServiceAccount
#################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-scheduler
  labels:
    tier: airflow
    component: scheduler
    release: airflow
