################################
## Airflow Worker ServiceAccount
#################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-worker
  labels:
    tier: airflow
    component: worker
    release: airflow

