######################################
## Airflow StatsD ServiceAccount
######################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-statsd
  labels:
    tier: airflow
    component: statsd
    release: airflow

