################################
## Airflow Fernet Key Secret
#################################
kind: Secret
apiVersion: v1
metadata:
  name: airflow-fernet-key
  labels:
    tier: airflow
    release: airflow
type: Opaque
data:
  fernet-key: "YVRFeWVFZFJSRUZVWTB4V2Qyd3hORzlhWmxkNGNGbHNlSGxHWkZWUGNFST0="
