################################
## Airflow Redis Password Secret
#################################
kind: Secret
apiVersion: v1
metadata:
  name: airflow-redis-password
  labels:
    tier: airflow
    component: redis
    release: airflow
type: Opaque
data:
  password: "eVlvUXVKbU5ReQ=="
---
##################################
## Airflow Redis Connection Secret
##################################
kind: Secret
apiVersion: v1
metadata:
  name: airflow-broker-url
  labels:
    tier: airflow
    component: redis
    release: airflow
type: Opaque
data:
  connection: "cmVkaXM6Ly86eVlvUXVKbU5ReUBhaXJmbG93LXJlZGlzOjYzNzkvMA=="
