#############################################
## Airflow Migrate Database Job ServiceAccount
##############################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-migrate-database-job
  labels:
    tier: airflow
    component: run-airflow-migrations
    release: airflow

