################################
## Airflow Metadata Secret
#################################
kind: Secret
apiVersion: v1
metadata:
  name: airflow-airflow-metadata
  labels:
    tier: airflow
    release: airflow
type: Opaque
data:
  connection: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGFpcmZsb3ctcG9zdGdyZXNxbC5haXJmbG93OjU0MzIvcG9zdGdyZXM/c3NsbW9kZT1kaXNhYmxl"
