################################
## Airflow Metadata Secret
#################################
kind: Secret
apiVersion: v1
metadata:
  name: airflow-airflow-metadata
  labels:
    tier: airflow
    release: airflow
type: Opaque
data:
  connection: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGFpcmZsb3ctcG9zdGdyZXNxbC5kZXYyZGV2LWFpcmZsb3c6NTQzMi9wb3N0Z3Jlcz9zc2xtb2RlPWRpc2FibGU="
