################################
## Airflow Triggerer ServiceAccount
#################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-triggerer
  labels:
    tier: airflow
    component: triggerer
    release: airflow

