######################################
## Airflow Webserver ServiceAccount
######################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-webserver
  labels:
    tier: airflow
    component: webserver
    release: airflow

