apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: airflow
  namespace: airflow
type: Opaque
data:
  postgresql-password: "cG9zdGdyZXM="
