apiVersion: v1
kind: Service
metadata:
  name: airflow-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: airflow
  namespace: airflow
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: airflow
    role: primary
