######################################
## Airflow Redis ServiceAccount
######################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-redis
  labels:
    tier: airflow
    component: redis
    release: airflow

