################################
## Airflow Redis StatefulSet
#################################
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: airflow-redis
  labels:
    tier: airflow
    component: redis
    release: airflow
spec:
  serviceName: airflow-redis
  selector:
    matchLabels:
      tier: airflow
      component: redis
      release: airflow
  template:
    metadata:
      labels:
        tier: airflow
        component: redis
        release: airflow
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      topologySpreadConstraints:
        []
      serviceAccountName: airflow-redis
      securityContext: 
        runAsUser: 0
      containers:
        - name: redis
          image: redis:6-bullseye
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          resources:
            {}
          args: ["-c", "redis-server --requirepass ${REDIS_PASSWORD}"]
          ports:
            - name: redis-db
              containerPort: 6379
          volumeMounts:
            - name: redis-db
              mountPath: /data
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-redis-password
                  key: password
  volumeClaimTemplates:
    - metadata:
        name: redis-db
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
